# Generated by Django 3.0.6 on 2020-05-31 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shipping_cose',
            new_name='shipping_cost',
        ),
    ]
